### ISSUE TITLE
Submit library to packagist

### ISSUE THREAD

**Issue by basdenooijer** [minimalcode-org/search#1]
Since "minimalcode/search" is now included as a suggestion in the Solarium composer config I think it should be submitted to Packagist. 
Currently the install fails because the package cannot be found.

**Comment by basdenooijer** [comment]
It seems like I overlooked something, it is available, just not in a stable version. Somehow I didn't find it in the packagist search engine, but now I do...

**Comment by dewos** [comment]
@basdenooijer  is you want I could tag a stable release. (
I was waiting for possible API changes, but the lib is pretty stable right now)

**Comment by basdenooijer** [comment]
I think it might be a good idea to indicate to people considering to use it that the library has reached a stable state .

**Comment by dewos** [comment]
Done. Tagged 1.0.1 stable.
Thanks @basdenooijer
