### ISSUE TITLE
operator precedence in nested criteria

### ISSUE THREAD

**Issue by revlis7** [minimalcode-org/search#14]
For nested criteria, if I try:

```php
$c1 = Criteria::where('age')
    ->is(24)
    ->andWhere('gender')
    ->is('male');

$c2 = Criteria::where('age')
    ->is(20)
    ->andWhere('gender')
    ->is('female');

$c1->orWhere($c2);

echo $c1;
```

I got:

`age:24 AND gender:male OR (age:20 AND gender:female)`

Solr will ignore all expressions after 'OR'

Here is another post talking about this: http://lucene.472066.n3.nabble.com/operator-precedence-and-confusing-result-td642263.html

The correct one should be:

`(age:24 AND gender:male) OR (age:20 AND gender:female)`

**Comment by dewos** [comment]
You should use connect()

**Comment by revlis7** [comment]
Oh that works! Didn't see this function in wiki page.

Thanks for the fast reply!

**Comment by dewos** [comment]
you're welcome
