### ISSUE TITLE
Fuzzy search, levenshtein distance float value deprecated

### ISSUE THREAD

**Issue by oligus** [minimalcode-org/search#4]
When doing fuzzy searches, Criteria only allows floating values between 0.0 and 1.0.

This is however deprecated in favour of integer values representing  maximum number of edits allowed. 

See:
https://lucene.apache.org/core/6_4_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Fuzzy_Searches

Affected method:
https://github.com/minimalcode-org/search/blob/master/src/Minimalcode/Search/Criteria.php#L411

I made a PR if you are interested.

**Comment by dewos** [comment]
Interesting, thank you @oligus 
This should be retro-compatible, right?

**Comment by dewos** [comment]
@oligus ping

**Comment by oligus** [comment]
Sorry, yes, it should be retro compatible, I shall fix that :-)

**Comment by dewos** [comment]
follow the mr 👍
